# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_destination', models.CharField(max_length=100)),
                ('trip_description', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('travellers', models.ManyToManyField(related_name='travellers', to='app_login.User')),
            ],
        ),
    ]
