# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_travel', '0002_auto_20170627_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travellers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travellerss', to='app_login.User'),
        ),
    ]
